#NO NEED FOR VERSION 3
version: '3'

services:
  nginx:
    #depends_on: wordpress
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    container_name: nginx_inception_c
    ports:
      - 443:443
    volumes:
      - type: bind
        source: ./requirements/nginx/conf.d/
        target: /etc/nginx/http.d/
      - type: bind
        source: ./requirements/nginx/tools/ssl/
        target: /etc/nginx/ssl/
      #FOR TESTING ONLY
      - type: bind
        source: ./requirements/nginx/tools/www/
        target: /var/www/
    # restart: always
  # wordpress:
  #   restart: always
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_PASS: ${DB_PASS}
        DB_USER: ${DB_USER}
        DB_ROOT: ${DB_ROOT}
    container_name: mariadb_inception_c
    restart: always

