version: '2'

services:
  nginx:
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
      args:
        CERT_: ${CERT_}
        KEY_: ${KEY_}
        DOMAIN_NAME: ${DOMAIN_NAME}
    image: nginx:inception
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - inception-nw
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - wp-volume:/var/www/
    restart: on-failure

  mariadb:
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    image: mariadb:inception
    container_name: mariadb
    # ports:
    #   - "3306:3306"
    networks:
      - inception-nw
    volumes:
      - db-volume:/var/lib/mysql
    restart: on-failure

  wordpress:
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DOMAIN_NAME: ${DOMAIN_NAME}
        WPADUSER: ${WPADUSER}
        WPADPASS: ${WPADPASS}
        WPUSER1: ${WPUSER1}
        WPUSER1PASS: ${WPUSER1PASS}
    image: wordpress:inception
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception-nw
    volumes:
      - wp-volume:/var/www/
    env_file:
      - ./.env
    restart: on-failure

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
    inception-nw:
        driver: bridge